<?php
# 設定ファイル（"SETTING.TXT"以外の設定項目）
# ログファイル保持数（システム設定）
define('KEEPLOGCOUNT', 4096);
# 1スレッドに投稿できるレス数の上限
define('THREAD_RES', 500);
# レスオーバー時のメッセージ
define('THREAD_MAX_MSG', 'あれ、<NUM>超えちゃったみたい…書き込めないや…<br>　　　 ∧∧ 　　　　　　　　　　 ∧,,∧<br>　　　（；ﾟДﾟ） 　　　　　　　　　ミﾟДﾟ,,彡 　おｋｋ<br>　　　ﾉ つ▼〔|￣￣］ 　　　　 ▽⊂　ﾐ 　　　新スレいこうぜ<br>　～（,,⊃〔￣||====]～～［］⊂,⊂,,,;;ﾐ@');
# 1スレッドの上限（バイト）
define('THREAD_BYTES', 524288);
# ファイルアップ許可
define('UPLOAD', 0);
# GDバージョン
// define('GD_VERSION', 2);
# アップロード上限（バイト）
define('MAX_BYTES', 300000);
# サムネイル画像の幅
define('MAX_W', 120);
# サムネイル画像の高さ
define('MAX_H', 160);
# おみくじ機能
define('OMIKUJI', 1);
# 野球機能
define('BASEBALL', 1);
# どこ誰何機能
define('WHO_WHERE', 1);
# 壷機能（未実装）
define('TUBO', 1);
# 等幅フォント機能
define('TELETYPE', 1);
# スレッド内名無し名変更機能
define('NAME_774', 1);
# 名無しへ強制変更機能
define('FORCE_774', 1);
# IDなし機能
define('FORCE_NO_ID', 1);
# sage強制機能
define('FORCE_SAGE', 1);
# レス要キャップ機能
define('FORCE_STARS', 1);
# スレッド内VIP機能解除
define('FORCE_NORMAL', 1);
# 名前入力強制機能
define('FORCE_NAME', 1);
# 0thelo機能
define('ZEROTHELO', 1);
# アップロード機能
define('FORCE_UP', 0);
?>
